### ISSUE TITLE
Stuck at starting up: "KSPBurst: waiting for Burst compiler..."

### ISSUE THREAD

**Issue by krisavi** [KSPModdingLibs/KSPBurst#3]
Not sure what is causing it. It started 5 min ago, but not any more, only change compared to last start is that this time it is using MM patches from cache.

In KSP.log
```
[EXC 23:08:46.650] InvalidOperationException: Collection was modified; enumeration operation may not execute.
	System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <9577ac7a62ef43179789031239ba8798>:0)
	System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <9577ac7a62ef43179789031239ba8798>:0)
	System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <9577ac7a62ef43179789031239ba8798>:0)
	KSPBurst.KSPBurst.FlushMessages () (at <c8b5fe2baff6415cb73ea658bdb44b4c>:0)
	KSPBurst.KSPBurst+<BurstCompile>d__20.MoveNext () (at <c8b5fe2baff6415cb73ea658bdb44b4c>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

and KSPBurst\info.log
```
Options processed in:                38ms
UpdateObjectFormatFromPlatform:       1ms
An unexpected exception occurred: 

```
and KSPBurst\error.log:
```
System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination (String parameters and return types must be paired with LPStr, LPWStr, LPTStr, BStr, TBStr, VBByRefStr, or AnsiBStr).
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointerInternal(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at Burst.Backend.StandardCompilerBackend..ctor(String nativeSharedLibraryName)
   at Burst.Backend.StandardCompilerBackend.GetSingleton(String backendName)
   at Burst.Bcl.BclApp..ctor(BclOptions options)
   at Burst.Bcl.Program.BuildTheThing(BclOptions options, Stopwatch& individualTimer)
   at Burst.Bcl.Program.Main(String[] args)

```

Even when game started, there were same errors in KSP.log: https://pastebin.com/pgkEzzs6

**Comment by siimav** [comment]
It got stuck on the loading screen with the exact same message in ksp.log.
[logs.zip](https://github.com/KSPModdingLibs/KSPBurst/files/12809240/logs.zip)

**Comment by JonnyOThan** [comment]
Saw a report that this was related to scansat.  And interestingly, scansat has a little `x` next to it in the assembly list for Burst.  But the error message is hinting that the background thread is adding more log/error messages while the main thread is outputting them, which seems real bad.
[Uploading KSP (3) (1).zip…]()

**Comment by Clayell** [comment]
Related: https://github.com/KSP-RO/RP-1/issues/2523#issuecomment-2671236157

> Saw a report that this was related to scansat.

This issue also pops up with the RP-1 Express Install, which usually doesn't include scansat.

**Comment by Gordon-Dry** [comment]
Here as well, with RP-1 Express Install.

The last 2 days since install I did not get this, but now. I added some suggested mods via CKAN, as mentioned here:
https://github.com/KSP-RO/RP-1/wiki/Extra-Mods-to-Consider#4-other-high-quality-parts-mods

Not all of them, this is my exported .ckan:
[RP-1 GD.zip](https://github.com/user-attachments/files/19536489/RP-1.GD.zip)

**Comment by JonnyOThan** [comment]
@Gordon-Dry that looks like a bug in RealAntennas

**Comment by Gordon-Dry** [comment]
This happens randomly. Yesterday I had it again for no reason, as I did not add, remove or alter anything prior starting KSP.
Kill process.
Start again.
No issue at all.

**Comment by Clayell** [comment]
Wait, that was it? KSPBurst will no longer get stuck on the loading screen? Huzzah! I'd definitely release that update now if you can.

**Comment by Gordon-Dry** [comment]
Sometimes it does. Sometimes not. Not reproducable.

**Comment by JonnyOThan** [comment]
> Sometimes it does. Sometimes not. Not reproducable.

Yes, that’s typically how race conditions behave.

I expect to get a release out tomorrow (today?).  I just need to figure out how to work this build system…
